### ISSUE TITLE
Allow search in directories starting with -

### ISSUE THREAD

**Issue by NHOrus** [kshvmdn/fsql#26]
As the pathname can contain `-`, it would be nice if there's explicit method of seeking in such directories.  
Or at least noted in README that to search in directory `-oops` you should do `./-oops`.

**Comment by kshvmdn** [comment]
Oops, completely neglected this as a possibility.

Right now, `-` is used to exclude a directory from the results, what are your thoughts on changing that symbol to `!` instead?

The downside here is that `!' is a reserved Shell character, so it'll have to be escaped in quote-less queries.

```
fsql SELECT all FROM ., \!-oops ...
```

**Comment by NHOrus** [comment]
Less shell escaping and slashes/backslashes, the best.
And least coding-intensive solution is to add my proposed solution to README.

**Comment by kshvmdn** [comment]
You're right.

The problem is, as of #25, we're normalizing directory names (this includes removing leading `./`). We aren't doing this until AFTER parsing the directory list, so it shouldn't be an immediate problem, but it's definitely something we have to keep in mind if we ever decide to update that.

I'll update the README with your suggestion for now. Thanks for the issue!

**Comment by jonesbrianc26** [comment]
I vote for a `!`, I don't see a way to denote excludes better than that. it may require an extra escape, but I can't think of a more ubiquitous symbol for expressing NOT that isn't interpreted by the shell.

**Comment by kshvmdn** [comment]
Just tested with `!`, turns out that even when the query is wrapped in quotes, it requires escaping, which is a little bit messy. Although I do agree with @jonesbrianc26 that `!` best represents NOT, will possibly look into allowing both.

I think for the time being, it'd be a better idea just to add a note in the README of how to deal with directories that begin with `-`, there's 2 ways right now:

1) As suggested by @NHOrus, to add a leading `./` (this is the only method that works in quote-less queries).

    ```
    fsql select all from ./-foo
    ```

2) Wrap the directory name in quotes.

    ```
    fsql "select all from '-foo'"
    ```
